name: Publish

on:
  push:
    branches: [experimental]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish articles on dev.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "content/posts/projects/ftp-automation.md"
          branch: experimental
          # (Optional) Use conventional commit messages. Default is false.
          # See https://www.conventionalcommits.org.
          conventional_commits: true
